# Generated by Django 4.2.3 on 2023-10-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="温度"
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="湿度"
                    ),
                ),
                ("led_num", models.IntegerField(verbose_name="LED开启数量")),
                (
                    "air_conditioner_status",
                    models.BooleanField(default=False, verbose_name="空调状态"),
                ),
            ],
        ),
    ]
