# Generated by Django 4.2.3 on 2023-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_datalog_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="datalog",
            name="ac_status",
            field=models.BooleanField(default=False, verbose_name="AC"),
        ),
        migrations.AddField(
            model_name="datalog",
            name="led_1_status",
            field=models.BooleanField(default=False, verbose_name="LED_1"),
        ),
        migrations.AddField(
            model_name="datalog",
            name="led_2_status",
            field=models.BooleanField(default=False, verbose_name="LED_2"),
        ),
        migrations.AddField(
            model_name="datalog",
            name="led_3_status",
            field=models.BooleanField(default=False, verbose_name="LED_3"),
        ),
    ]
