# Generated by Django 4.2.3 on 2023-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_datalog_ac_status_datalog_led_1_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datalog",
            name="led_num",
            field=models.PositiveIntegerField(verbose_name="LED开启数量"),
        ),
    ]
