# Generated by Django 4.2.3 on 2023-11-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_datalog_led_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datalog",
            name="air_conditioner_status",
        ),
    ]
